#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShelterHelper
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ShelterHelper")]
	public partial class AwesomePetsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public AwesomePetsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ShelterHelperConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AwesomePetsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AwesomePetsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AwesomePetsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AwesomePetsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AnimalInventory> AnimalInventories
		{
			get
			{
				return this.GetTable<AnimalInventory>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AnimalInventory")]
	public partial class AnimalInventory
	{
		
		private string _AnimalID;
		
		private string _Animal_Type;
		
		private string _Intake_Date;
		
		private string _Name;
		
		private string _Breed;
		
		private string _Estimated_Age;
		
		private string _Sex;
		
		private string _Size;
		
		private string _Kennel_Number;
		
		private string _Intake_Type;
		
		private string _Intake_Subtype;
		
		private string _Kennel_Status;
		
		private string _Zip_Where_Found;
		
		private string _Primary_Color;
		
		private string _Description;
		
		public AnimalInventory()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnimalID", DbType="VarChar(50)")]
		public string AnimalID
		{
			get
			{
				return this._AnimalID;
			}
			set
			{
				if ((this._AnimalID != value))
				{
					this._AnimalID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Animal Type]", Storage="_Animal_Type", DbType="VarChar(50)")]
		public string Animal_Type
		{
			get
			{
				return this._Animal_Type;
			}
			set
			{
				if ((this._Animal_Type != value))
				{
					this._Animal_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Intake Date]", Storage="_Intake_Date", DbType="VarChar(50)")]
		public string Intake_Date
		{
			get
			{
				return this._Intake_Date;
			}
			set
			{
				if ((this._Intake_Date != value))
				{
					this._Intake_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Breed", DbType="VarChar(50)")]
		public string Breed
		{
			get
			{
				return this._Breed;
			}
			set
			{
				if ((this._Breed != value))
				{
					this._Breed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Estimated Age]", Storage="_Estimated_Age", DbType="VarChar(50)")]
		public string Estimated_Age
		{
			get
			{
				return this._Estimated_Age;
			}
			set
			{
				if ((this._Estimated_Age != value))
				{
					this._Estimated_Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="VarChar(50)")]
		public string Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this._Sex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="VarChar(50)")]
		public string Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this._Size = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Kennel Number]", Storage="_Kennel_Number", DbType="VarChar(50)")]
		public string Kennel_Number
		{
			get
			{
				return this._Kennel_Number;
			}
			set
			{
				if ((this._Kennel_Number != value))
				{
					this._Kennel_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Intake Type]", Storage="_Intake_Type", DbType="VarChar(50)")]
		public string Intake_Type
		{
			get
			{
				return this._Intake_Type;
			}
			set
			{
				if ((this._Intake_Type != value))
				{
					this._Intake_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Intake Subtype]", Storage="_Intake_Subtype", DbType="VarChar(50)")]
		public string Intake_Subtype
		{
			get
			{
				return this._Intake_Subtype;
			}
			set
			{
				if ((this._Intake_Subtype != value))
				{
					this._Intake_Subtype = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Kennel Status]", Storage="_Kennel_Status", DbType="VarChar(50)")]
		public string Kennel_Status
		{
			get
			{
				return this._Kennel_Status;
			}
			set
			{
				if ((this._Kennel_Status != value))
				{
					this._Kennel_Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Zip Where Found]", Storage="_Zip_Where_Found", DbType="VarChar(50)")]
		public string Zip_Where_Found
		{
			get
			{
				return this._Zip_Where_Found;
			}
			set
			{
				if ((this._Zip_Where_Found != value))
				{
					this._Zip_Where_Found = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Primary Color]", Storage="_Primary_Color", DbType="VarChar(50)")]
		public string Primary_Color
		{
			get
			{
				return this._Primary_Color;
			}
			set
			{
				if ((this._Primary_Color != value))
				{
					this._Primary_Color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(5000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
